server:
    port: 8088
    
logging:
    level:
        root: ERROR
        uk:
            gov:
                hmrc: TRACE
tax:
    authUrl: https://test-api.service.hmrc.gov.uk/
    redirectUrl: https://localhost
    scope: common-transit-convention-traders
    submitDepartureDeclarationUrl: ${tax.authUrl}customs/transits/movements/departures
    secret: change-me
    clientId: change-me
    acceptHeader: application/vnd.hmrc.1.0+json


